In [1]:
import torch
import random
import numpy as np
torch.__version__

'2.4.1+cu121'

# Tensors

## Creating Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar, scalar.ndim, scalar.item()

(tensor(7), 0, 7)

In [ ]:
# vector
vector = torch.tensor([2,3,4])
vector, vector.ndim

(tensor([2, 3, 4]), 1)

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
# Matrix
Matrx = torch.tensor([[7,8],
                      [9,10]])
Matrx, Matrx.ndim, Matrx.shape

(tensor([[ 7,  8],
         [ 9, 10]]),
 2,
 torch.Size([2, 2]))

In [ ]:
# other
tns = torch.tensor([
    [[1,2],
     [2,3],
     [5,6]]
])
tns.shape

torch.Size([1, 3, 2])

## Random Tensors

In [ ]:
# random tensor of size (3, 4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.6348, 0.2591, 0.8804, 0.3650],
         [0.2704, 0.7608, 0.2354, 0.7321],
         [0.9170, 0.3355, 0.5067, 0.0457]]),
 torch.float32)

## Zeros and ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
# all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Creating a range and tensors like

In [2]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# zero tensor of similar shape
ten_zero = torch.zeros_like(input = zero_to_ten)

ten_ones = torch.ones_like(input = ten_zero)

print(ten_zero, ten_ones)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


## Tensor datatype

In [22]:
f32_tensor = torch.tensor([3.0, 2.0],
                          dtype=None,
                          device=None,
                          requires_grad=False)
f16_tensor = torch.tensor([3.0, 2.0],
                          dtype=torch.float16)


In [23]:
print(f"{'Tensor':<10} {'Shape':<20} {'Dtype':<20} {'Device':<15}")
print(f"{'f32':<10} {str(f32_tensor.shape):<20} {str(f32_tensor.dtype):<20} {str(f32_tensor.device):<15}")
print(f"{'f16':<10} {str(f16_tensor.shape):<20} {str(f16_tensor.dtype):<20} {str(f16_tensor.device):<15}")


Tensor     Shape                Dtype                Device         
f32        torch.Size([2])      torch.float32        cpu            
f16        torch.Size([2])      torch.float16        cpu            


# Getting info from tensors

In [30]:
some_tensor = torch.rand(size=(3,4))
print(f"{'Tensor':<15} : {some_tensor}")
print(f"{'Shape':<15} : {some_tensor.shape}" )
print(f"{'Dtype':<15} : {some_tensor.dtype}" )
print(f"{'Device':<15} : {some_tensor.device}" )

Tensor          : tensor([[0.6736, 0.7322, 0.6362, 0.9709],
        [0.0465, 0.4670, 0.6297, 0.6304],
        [0.7475, 0.5143, 0.7807, 0.6105]])
Shape           : torch.Size([3, 4])
Dtype           : torch.float32
Device          : cpu


# Manipulating Tensor

## Basic operations

In [32]:
tensor = torch.tensor([1,2,3])
tensor + 10, tensor *10

(tensor([11, 12, 13]), tensor([10, 20, 30]))

In [33]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

## Matrix multiplication

In [35]:
tensor = torch.tensor([1,2,3])
print("Element-wise multiplication : ", tensor * tensor)
print("Matrix Mult : ", torch.matmul(tensor, tensor))
print("Matrix Mult : ", tensor @ tensor)

Element-wise multiplication :  tensor([1, 4, 9])
Matrix Mult :  tensor(14)
Matrix Mult :  tensor(14)


## Transpose

In [37]:
tensor = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
tensor, tensor.T

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[1., 3., 5.],
         [2., 4., 6.]]))

# Common errors in DL (shape errors)

## Min, Max, Mean, Sum etc

In [42]:
x = torch.arange(start = 0, end = 100, step = 10)
print(f"{'Min': <10} : {x.min()}")
print(f"{'Max': <10} : {x.max()}")
print(f"{'Mean': <10} : {x.type(torch.float32).mean()}")
print(f"{'Sum': <10} : {x.sum()}")



Min        : 0
Max        : 90
Mean       : 45.0
Sum        : 450


## Positional min/max

In [43]:
tensor = torch.arange(0, 100, step = 10)
print("tensor : ", tensor)
print("index of max value : ", tensor.argmax())
print("index of min value : ", tensor.argmin())

tensor :  tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
index of max value :  tensor(9)
index of min value :  tensor(0)


## Change tensor datatype

In [44]:
tensor = torch.arange(10. , 100. , 10.)
tensor.dtype

torch.float32

In [45]:
# convert to float16
tensor_16f = tensor.type(torch.float16)
tensor_16f.dtype

torch.float16

In [47]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8.dtype

torch.int8

## Reshaping, stacking, squeezing, unsqueezing

In [48]:
x = torch.arange(1., 8)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [49]:
# add extra dim
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [52]:
# Change the view (keep same data as original but change the view)
# NOTE : changing the view also change the original tensor as well
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [53]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [60]:
# stack the tensor
x_stacked_dim0 = torch.stack([x, x, x], dim = 0)
x_stacked_dim1 = torch.stack([x, x, x], dim = 1)
x_stacked_dim0, x_stacked_dim1

(tensor([[5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.],
         [5., 2., 3., 4., 5., 6., 7.]]),
 tensor([[5., 5., 5.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.]]))

In [61]:
# remove all single dim from tensor
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [67]:
# add dimension of 1 at specific index
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7.]])

In [73]:
# rearrange the axis of tensor
x_original = torch.rand(size=(224, 224, 3))
# shift axis such that 0=1 , 1=2, 2=0
x_premuted = x_original.permute(2, 0, 1)
print(f"{'original tensor shape' :<15} : {x_original.shape}")
print(f"{'permuted tensor shape' :<15} : {x_premuted.shape}")

original tensor shape : torch.Size([224, 224, 3])
permuted tensor shape : torch.Size([3, 224, 224])


# Indexing

In [74]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [75]:
x[0], x[0][0], x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

# Pytorch tensor and NumPy

In [81]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor
# array is of float64 type default

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [80]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility
`torch.random.manual_seed(seed=RANDOM_SEED)`

In [86]:
RANDOM_SEED = 47
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor = torch.rand(3,4)

# Running tensors on GPU

In [2]:
!nvidia-smi

Mon Oct  7 10:17:11 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
torch.cuda.is_available()

True

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# number of available cuda device
torch.cuda.device_count()

1

In [6]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available
device

'cuda'

## Putting tensor on GPU

In [7]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor_on_GPU = tensor.to(device)
print(tensor_on_GPU, tensor_on_GPU.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0


## Tensor back to CPU

In [10]:
tensor_on_GPU.cpu().numpy()

array([1, 2, 3])